# Generated by Django 2.2.13 on 2022-04-04 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_merge_20220205_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('background', models.CharField(choices=[('Finance', 'Finance'), ('Operations', 'Operations'), ('Security', 'Security')], max_length=50)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=2)),
                ('probability_percentage', models.CharField(choices=[('ZERO_PERCENT', '0%'), ('TEN_PERCENT', '10%'), ('TWENTY_PERCENT', '20%'), ('THIRTY_PERCENT', '30%'), ('FORTY_PERCENT', '40%'), ('FIFTY_PERCENT', '50%'), ('SIXTY_PERCENT', '60%'), ('SEVENTY_PERCENT', '70%'), ('EIGHTY_PERCENT', '80%'), ('NINETY_PERCENT', '90%'), ('HUNDRED_PERCENT', '100%')], max_length=2)),
                ('impact', models.CharField(max_length=120)),
                ('status', models.CharField(max_length=120)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assignee', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
