# Generated by Django 2.2.13 on 2022-04-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='probability_percentage',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('8%', '80%'), ('9%', '90%'), ('100%', '100%')], max_length=2),
        ),
        migrations.AlterField(
            model_name='risk',
            name='severity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=2),
        ),
    ]
