# Generated by Django 2.2.13 on 2022-04-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20220404_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='probability_percentage',
            field=models.CharField(choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], max_length=3),
        ),
    ]
