# Generated by Django 2.2.13 on 2022-04-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220406_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='background',
        ),
    ]
