# Generated by Django 2.2.13 on 2022-04-06 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_remove_risk_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='probability_percentage',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='status',
        ),
        migrations.AddField(
            model_name='risk',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='probability',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
