# Generated by Django 2.2.13 on 2022-04-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220406_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='mitigation_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
